### ISSUE TITLE
ch 3.6.1, The Constant Generator iota

### ISSUE THREAD

**Issue by chai2010** [adonovan/gopl.io#10]
> In a const declaration, the value of iota begins at zero and increments by one for each item in the sequence.

The iota only increments by one line for each item.

```Go
type Weekday int

const (
	Sunday, A Weekday = iota, iota

	Monday, B
)

func main() {
	println(Sunday, A)
	println(Monday, B)
}
```

Output:

```
0 0
1 1
```

**Comment by alandonovan** [comment]
You are correct that `iota` increments by one per line (technically per `ConstSpec`, as the grammar in the Go language specification calls it), not one per named constant on the line.  However, it is extremely rare to declare two constants on the same line, both of which refer to `iota`, since you can achieve the same effect more simply by using two separate `const` declarations.  For that reason, we chose not to complicate the presentation by being entirely explicit about this detail.
