### ISSUE TITLE
P189,Section 7.6

### ISSUE THREAD

**Issue by foreversmart** [adonovan/gopl.io#17]
"Len and Swap, the other two methods of reverse, are implicitly provided by the original sort.Interface value because it is an embedded field. The exported function Reverse returns an instance of the reverse type that contains the original sort.Interface value."

I think this would be better:

"Len and Swap, the other two methods of reverse, are implicitly provided by the original sort.Interface value which it is an embedded field. Because reverse is an unexported type, the exported function Reverse returns an instance of the reverse type that contains the original sort.Interface value."

**Comment by adonovan** [comment]
The word "because" is appropriate: if the `sort.Interface` field was named, not anonymous, it would not contribute the `Len` and `Swap` methods to the `reverse` type.  It is crucial that it be anonymous.

Conversely, in the alternative wording, "Because" is not appropriate: for this pattern to work, it is not necessary that the type `reverse` is unexported and the function `Reverse` is exported; it is merely a passing observation.  If you want, you can apply this pattern within a single package using only unexported identifiers.
