### ISSUE TITLE
errata, page 68

### ISSUE THREAD

**Issue by ak2196** [adonovan/gopl.io#3]
The UTF-8 table on page 68 is wrong. The first bytes should be 0xxxxxxx, 110xxxxx, 1110xxxx, 11110xxx respectively.

**Comment by ak2196** [comment]
The other problem seems to be the upper limit on the 4 byte characters. It should be 0x1fffff instead of 0x10ffff.

**Comment by bkernighan** [comment]
You're absolutely right on the first one; some editing command seems to have gone awry at a late stage, deleting the 3rd character of the first column.  The correct version is posted on the errata page and will be fixed in the next printing.
The second one is actually correct as is.  Says Wikipedia:  "In November 2003, UTF-8 was restricted by RFC 3629 to end at U+10FFFF, in order to match the constraints of the UTF-16 character encoding."  This is the value of the constant utf8.MaxRune.

**Comment by ak2196** [comment]
Of course you are absolutely correct. Thank you for explaining that and the quick reply. Excellent writing as usual.
