### ISSUE TITLE
ch13/bzip: example violates pointer passing rules

### ISSUE THREAD

**Issue by dsnet** [adonovan/gopl.io#4]
using ```go1.5.1```.

According to the [Proposal 12416](https://github.com/golang/proposal/blob/master/design/12416-cgo-pointers.md):
>The de-facto rule for 1.4 is: you can pass any Go pointer to C. C code may use it freely. If C code stores the Go pointer in C memory then there must be a live copy of the pointer in Go as well. You can allocate Go memory in C code by calling the Go function _cgo_allocate.
>
>The de-facto rule for 1.5 adds restrictions. You can still pass any Go pointer to C. **However, C code may not store a Go pointer in Go memory** (C code can still store a Go pointer in C memory, with the same restrictions as in 1.4). The _cgo_allocate function has been removed.

From what I can understand, this is exactly what is happening in the example:

1. [Go pointers are passed to C](https://github.com/adonovan/gopl.io/blob/30090035dea568fd70cbcef194a06fbe32ae2199/ch13/bzip/bzip2.go#L53-L55)
2. C code is  [storing Go pointers](https://github.com/adonovan/gopl.io/blob/30090035dea568fd70cbcef194a06fbe32ae2199/ch13/bzip/bzip2.c#L13-L16) in [Go memory](https://github.com/adonovan/gopl.io/blob/30090035dea568fd70cbcef194a06fbe32ae2199/ch13/bzip/bzip2.go#L37)

**Comment by adonovan** [comment]
The gopl.io/ch13/bzip program would indeed not be legal under the rules proposed by issue 12416. The program should allocate the bz_stream variable from C code using malloc, and must therefore explicitly release it from C code using free immediately after the call to BZ2_CompressEnd.  Under the de facto 1.5 rules, this program runs correctly because, although it stores a Go pointer into the Go heap from C code, this pointer is never used after the C call returns.  In contrast, the proposed rules outlaw even temporary assignments of this kind.

Thanks for pointing out this regrettable error.

If there is a moral to this story, it is that even the most carefully reviewed cgo programs contain subtle bugs. :(

**Comment by bkernighan** [comment]
Given the fact that it "works" (albeit more by good luck than anything
else), we should leave it alone for now.  I suppose a suitable errata
entry would be ok, but the fact that it fails under "proposed rules"
seems to mitigate the problem a bit.

**Comment by dsnet** [comment]
Fortunately, the section on cgo is at the end of the book is not the primary focus of the book (which otherwise does a fantastic job teaching Go itself). An errata entry would probably be appropriate, but I do vote for some change to the code itself.  

I actually used this code as an example and tried adapting it to wrap some other C library, and kept running into GC errors: ```fatal error: objectstart: bad pointer in unexpected span```. It was not obvious to me why my modification of this example caused my code to be invalid.

After struggling with it for hours, I eventually adapted the [cgzip example from youtube](https://github.com/youtube/vitess/blob/master/go/cgzip/zstream.go#L86-L89) as starting point instead and managed to get it to work. But as [Ian Lance Taylor mentioned](https://groups.google.com/forum/#!msg/golang-nuts/Pw90LA0ksMs/fnbhroQFAgAJ), it is actually still incorrect.

Given that this ch13/bzip is used by people to be a reference for wrapping C libraries, it probably makes sense to write an example that is as correct as possible (especially, in light of the large number of bad/incorrect wrappers already out there).

**Comment by adonovan** [comment]
We have updated `gopl.io/ch13/bzip` so that it defines and calls C functions to allocate the bz_stream variable, and so that it clears out the Go pointers that it temporarily stores into the bz_stream variable.  

We have retained the original version that appears in print as `gopl.io/ch13/bzip-print`.

Thanks again for pointing out this regrettable error.
